# permissions for end users to edit echoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: echo-editor-role
rules:
- apiGroups:
  - gogogo.yangsijie666.github.com
  resources:
  - echoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gogogo.yangsijie666.github.com
  resources:
  - echoes/status
  verbs:
  - get
